# Generated by Django 5.1.1 on 2025-02-03 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kra_id', models.CharField(max_length=100)),
                ('kra_questions', models.TextField()),
                ('answer_type', models.CharField(max_length=50)),
                ('activate', models.BooleanField(default=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('emp_code', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('answer', models.TextField()),
                ('user_rating', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('primary_reviewer_id', models.IntegerField()),
                ('secondary_reviewer_id', models.IntegerField()),
                ('emp_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pmsapp.login', to_field='emp_code')),
                ('kra_id', models.ManyToManyField(related_name='user', to='pmsapp.kra')),
            ],
        ),
        migrations.CreateModel(
            name='PlanOfAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('poa', models.TextField(blank=True)),
                ('poa_points', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('year', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmsapp.user')),
            ],
        ),
    ]
