# Generated by Django 4.2.14 on 2025-02-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KraId',
            fields=[
                ('kra_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(max_length=10)),
                ('department', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='kra',
            name='kra_id',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='pmsapp.kraid'),
        ),
    ]
