# Generated by Django 4.2.14 on 2025-02-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmsapp', '0002_kraid_alter_kra_kra_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kra',
            name='kra_questions',
            field=models.TextField(null=True),
        ),
    ]
