# Generated by Django 4.2.14 on 2025-02-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmsapp', '0003_alter_kra_kra_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kraid',
            old_name='kra_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='kraid',
            name='year',
            field=models.IntegerField(),
        ),
    ]
